package com.demo.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCoure<M extends BaseCoure<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setCoureName(java.lang.String coureName) {
		set("coureName", coureName);
		return (M)this;
	}
	
	public java.lang.String getCoureName() {
		return getStr("coureName");
	}

	public M setScore(java.lang.String score) {
		set("score", score);
		return (M)this;
	}
	
	public java.lang.String getScore() {
		return getStr("score");
	}

	public M setKind(java.lang.String kind) {
		set("kind", kind);
		return (M)this;
	}
	
	public java.lang.String getKind() {
		return getStr("kind");
	}

}
