package com.demo.model;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.Record;
/**
 * Generated by JFinal, do not modify this file.
 */
public class BaseStudent extends Model<BaseStudent> {
	public Integer setId(java.lang.Integer id) {
		set("id", id);
		return id;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public String setName(java.lang.String name) {
		set("name", name);
		return name;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public String setPhone(java.lang.String phone) {
		set("phone", phone);
		return phone;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public String setSex(java.lang.String sex) {
		set("sex", sex);
		return sex;
	}
	
	public java.lang.String getSex() {
		return getStr("sex");
	}

	public String setIsdeleted(java.lang.String isdeleted) {
		set("isdeleted", isdeleted);
		return isdeleted;
	}
	
	public java.lang.String getIsdeleted() {
		return getStr("isdeleted");
	}

	public Integer setCourId(java.lang.Integer courId) {
		set("courId", courId);
		return courId;
	}
	
	public java.lang.Integer getCourId() {
		return getInt("courId");
	}
	public String setSchool(java.lang.String school) {
		set("school", school);
		return school;
	}
	
	public java.lang.String getSchool() {
		return getStr("school");
	}
     public void setRecord(Record r){
    	 Integer agr0 = 0;
 		Object ob0 = r.get("id");
 		agr0 =(Integer) ob0;
 		setId(agr0);
 		String agr1 = "";
 		Object ob1 = r.get("name");
 		agr1 = ob1+"";
 		setName(agr1);
 		/*Date agr2 = null;
 		Object ob2 = r.get("USER_KSSJ");
 		if(ob2 instanceof java.sql.Timestamp){
 		agr2 = new Date(((java.sql.Timestamp)ob2).getTime());
 		}else if(ob2 instanceof java.sql.Date){
 		agr2 = new Date(((java.sql.Date)ob2).getTime());}
 		setUserKssj(agr2);*/
 		String agr3 = "";
 		Object ob3 = r.get("phone");
 		agr3 = ob3+"";
 		setPhone(agr3);
 		String agr4 = "";
 		Object ob4 = r.get("sex");
 		agr4 = ob4+"";
 		setSex(agr4);
 		Integer agr5 =0;
 		Object ob5 = r.get("courId");
 		agr5=(Integer) ob5;
 		setCourId(agr5);
 		String agr6 = "";
 		Object ob6 = r.get("isdeleted");
 		agr6 = ob6+"";
 		setIsdeleted(agr6);
 		String agr7="";
 		Object ob7=r.get("school");
 		agr7=ob7+"";
 		setSchool(agr7);
     }
}
