package com.demo.model;

import com.demo.model.BaseCoure;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Coure extends BaseCoure<Coure> {
	public static final Coure dao = new Coure().dao();
}
