package com.demo.model;

import com.demo.model.bean.BasePersonLoginInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonLoginInfo extends BasePersonLoginInfo<PersonLoginInfo> {
	public static final PersonLoginInfo dao = new PersonLoginInfo().dao();
}
