package com.demo.model;

import com.demo.model.BaseStudent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Student extends BaseStudent {
	public static final Student dao = new Student();
}
