package com.demo.model.bean;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.Record;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStudent<M extends BaseStudent<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setSex(java.lang.String sex) {
		set("sex", sex);
		return (M)this;
	}
	
	public java.lang.String getSex() {
		return getStr("sex");
	}

	public M setIsdeleted(java.lang.String isdeleted) {
		set("isdeleted", isdeleted);
		return (M)this;
	}
	
	public java.lang.String getIsdeleted() {
		return getStr("isdeleted");
	}

	public M setCourId(java.lang.Integer courId) {
		set("courId", courId);
		return (M)this;
	}
	
	public java.lang.Integer getCourId() {
		return getInt("courId");
	}

	public M setSchool(java.lang.String school) {
		set("school", school);
		return (M)this;
	}
	
	public java.lang.String getSchool() {
		return getStr("school");
	}
	public void setRecord(Record r){
   	 Integer agr0 = 0;
		Object ob0 = r.get("id");
		agr0 =(Integer) ob0;
		setId(agr0);
		String agr1 = "";
		Object ob1 = r.get("name");
		agr1 = ob1+"";
		setName(agr1);
		/*Date agr2 = null;
		Object ob2 = r.get("USER_KSSJ");
		if(ob2 instanceof java.sql.Timestamp){
		agr2 = new Date(((java.sql.Timestamp)ob2).getTime());
		}else if(ob2 instanceof java.sql.Date){
		agr2 = new Date(((java.sql.Date)ob2).getTime());}
		setUserKssj(agr2);*/
		String agr3 = "";
		Object ob3 = r.get("phone");
		agr3 = ob3+"";
		setPhone(agr3);
		String agr4 = "";
		Object ob4 = r.get("sex");
		agr4 = ob4+"";
		setSex(agr4);
		Integer agr5 =0;
		Object ob5 = r.get("courId");
		agr5=(Integer) ob5;
		setCourId(agr5);
		String agr6 = "";
		Object ob6 = r.get("isdeleted");
		agr6 = ob6+"";
		setIsdeleted(agr6);
		String agr7="";
		Object ob7=r.get("school");
		agr7=ob7+"";
		setSchool(agr7);
    }
}
